/**
 * seed-catalog.ts — a STARTER tool catalog for the AI Audit Stack engine.
 *
 * The catalog is DATA, not logic. This is a small, hand-curated seed so the
 * engine is runnable and testable today; the real product replaces it with a
 * large, fresh, niche-aware catalog (Kaggle 3,495 seed + MIT lists, curated —
 * see docs/product-ai-audit-stack.md). Every number here is a PLAUSIBLE
 * ESTIMATE and must be verified before it appears in a client-facing report —
 * honesty rule: audits must be real or fail honestly.
 *
 * Every tool is tagged with the five business ENGINES it serves (attract,
 * convert, deliver, retain, run) and the NICHES/industries it fits, so a
 * clinic's Convert/Run gargalos surface clinic tools, not "use ChatGPT"
 * (capilaridade, founder 2026-08-14).
 *
 * Pain vocabulary: content-volume · customer-support-load · meeting-notes ·
 * lead-research · repetitive-tasks · data-analysis · video-editing ·
 * social-scheduling · email-overload · seo-visibility · design-assets ·
 * no-shows · reviews · phone-answering · appointment-scheduling · billing-admin.
 */

import type { Tool } from "./types";

export const SEED_CATALOG: Tool[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    url: "https://chat.openai.com",
    category: "writing",
    niches: [],
    pains: ["content-volume", "repetitive-tasks", "email-overload"],
    engines: ["attract", "deliver", "run"],
    monthlyCostUsd: 20,
    setupEffort: "low",
    impact: "high",
    hoursSavedWeekly: 5,
    oneLiner: "General-purpose assistant for drafts, replies and quick analysis.",
    isGeneric: true,
  },
  {
    id: "claude",
    name: "Claude",
    url: "https://claude.ai",
    category: "writing",
    niches: [],
    pains: ["content-volume", "data-analysis", "repetitive-tasks"],
    engines: ["deliver", "run"],
    monthlyCostUsd: 20,
    setupEffort: "low",
    impact: "high",
    hoursSavedWeekly: 5,
    oneLiner: "Long-context assistant strong at documents, analysis and code.",
    isGeneric: true,
  },
  {
    id: "jasper",
    name: "Jasper",
    url: "https://jasper.ai",
    category: "marketing",
    niches: ["agency", "ecommerce"],
    pains: ["content-volume", "seo-visibility"],
    engines: ["attract"],
    monthlyCostUsd: 49,
    setupEffort: "medium",
    impact: "medium",
    hoursSavedWeekly: 4,
    oneLiner: "Brand-tuned marketing copy at volume across channels.",
  },
  {
    id: "fireflies",
    name: "Fireflies.ai",
    url: "https://fireflies.ai",
    category: "meetings",
    niches: [],
    pains: ["meeting-notes"],
    engines: ["run"],
    monthlyCostUsd: 18,
    setupEffort: "low",
    impact: "medium",
    hoursSavedWeekly: 3,
    oneLiner: "Records, transcribes and summarizes meetings automatically.",
  },
  {
    id: "intercom-fin",
    name: "Intercom Fin",
    url: "https://intercom.com/fin",
    category: "support",
    niches: ["saas", "ecommerce"],
    pains: ["customer-support-load", "email-overload"],
    engines: ["retain", "run"],
    monthlyCostUsd: 99,
    setupEffort: "high",
    impact: "high",
    hoursSavedWeekly: 8,
    oneLiner: "AI agent that resolves front-line support tickets on its own.",
  },
  {
    id: "apollo",
    name: "Apollo.io",
    url: "https://apollo.io",
    category: "sales",
    niches: ["saas", "agency"],
    pains: ["lead-research"],
    engines: ["attract", "convert"],
    monthlyCostUsd: 49,
    setupEffort: "medium",
    impact: "high",
    hoursSavedWeekly: 6,
    oneLiner: "Finds, enriches and sequences outbound leads.",
  },
  {
    id: "make",
    name: "Make",
    url: "https://make.com",
    category: "ops",
    niches: [],
    pains: ["repetitive-tasks", "email-overload"],
    engines: ["run", "deliver"],
    monthlyCostUsd: 16,
    setupEffort: "high",
    impact: "high",
    hoursSavedWeekly: 7,
    oneLiner: "Visual automation to connect apps and kill manual busywork.",
  },
  {
    id: "zapier",
    name: "Zapier",
    url: "https://zapier.com",
    category: "ops",
    niches: [],
    pains: ["repetitive-tasks"],
    engines: ["run"],
    monthlyCostUsd: 30,
    setupEffort: "low",
    impact: "medium",
    hoursSavedWeekly: 4,
    oneLiner: "No-code automations between the tools you already use.",
  },
  {
    id: "opus-clip",
    name: "Opus Clip",
    url: "https://opus.pro",
    category: "video",
    niches: ["creator", "agency"],
    pains: ["video-editing", "content-volume"],
    engines: ["attract"],
    monthlyCostUsd: 29,
    setupEffort: "low",
    impact: "medium",
    hoursSavedWeekly: 4,
    oneLiner: "Turns long videos into ready-to-post short clips.",
  },
  {
    id: "buffer",
    name: "Buffer",
    url: "https://buffer.com",
    category: "marketing",
    niches: [],
    pains: ["social-scheduling", "content-volume"],
    engines: ["attract"],
    monthlyCostUsd: 12,
    setupEffort: "low",
    impact: "medium",
    hoursSavedWeekly: 3,
    oneLiner: "Schedules and drafts social posts across channels.",
  },
  {
    id: "gamma",
    name: "Gamma",
    url: "https://gamma.app",
    category: "design",
    niches: ["agency", "consulting"],
    pains: ["design-assets", "content-volume"],
    engines: ["attract", "deliver"],
    monthlyCostUsd: 10,
    setupEffort: "low",
    impact: "medium",
    hoursSavedWeekly: 2,
    oneLiner: "Generates polished decks and one-pagers from a prompt.",
  },
  {
    id: "hex",
    name: "Hex",
    url: "https://hex.tech",
    category: "data",
    niches: ["saas"],
    pains: ["data-analysis"],
    engines: ["run", "deliver"],
    monthlyCostUsd: 36,
    setupEffort: "high",
    impact: "high",
    hoursSavedWeekly: 6,
    oneLiner: "Notebook + AI for exploring and sharing data analyses.",
  },
  // Vertical tools: the capilaridade proof. A dental clinic gets these, not
  // ChatGPT, because they are tagged to the clinic's niche + Convert/Run engines
  // and its real gargalos (no-shows, phone, reviews, scheduling, billing).
  {
    id: "weave",
    name: "Weave",
    url: "https://getweave.com",
    category: "clinic-ops",
    niches: ["clinic", "dental", "local-service"],
    pains: ["phone-answering", "no-shows", "reviews", "appointment-scheduling"],
    engines: ["convert", "retain", "run"],
    monthlyCostUsd: 99,
    setupEffort: "medium",
    impact: "high",
    hoursSavedWeekly: 8,
    oneLiner: "Phone, texts, reviews and reminders for local clinics in one place.",
  },
  {
    id: "nexhealth",
    name: "NexHealth",
    url: "https://nexhealth.com",
    category: "clinic-ops",
    niches: ["clinic", "dental"],
    pains: ["appointment-scheduling", "no-shows", "billing-admin"],
    engines: ["convert", "run"],
    monthlyCostUsd: 79,
    setupEffort: "medium",
    impact: "high",
    hoursSavedWeekly: 6,
    oneLiner: "Online booking, reminders and paperwork for dental and medical practices.",
  },
  {
    id: "podium",
    name: "Podium",
    url: "https://podium.com",
    category: "reviews",
    niches: ["clinic", "dental", "local-service", "restaurant"],
    pains: ["reviews", "phone-answering"],
    engines: ["attract", "retain"],
    monthlyCostUsd: 89,
    setupEffort: "low",
    impact: "medium",
    hoursSavedWeekly: 4,
    oneLiner: "Collects reviews and answers customer messages for local businesses.",
  },
];
