/**
 * seed-catalog.ts — a STARTER tool catalog for the AI Audit Stack engine.
 *
 * The catalog is DATA, not logic. This is a small, hand-curated seed so the
 * engine is runnable and testable today; the real product replaces it with a
 * large, fresh, niche-aware catalog (Kaggle 3,495 seed + MIT lists, curated —
 * see docs/product-ai-audit-stack.md). Every number here is a PLAUSIBLE
 * ESTIMATE and must be verified before it appears in a client-facing report —
 * honesty rule: audits must be real or fail honestly.
 *
 * Pain vocabulary (the questionnaire offers these slugs; tools tag which they
 * address): content-volume · customer-support-load · meeting-notes ·
 * lead-research · repetitive-tasks · data-analysis · video-editing ·
 * social-scheduling · email-overload · seo-visibility · design-assets.
 */

import type { Tool } from "./types";

export const SEED_CATALOG: Tool[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    url: "https://chat.openai.com",
    category: "writing",
    niches: [],
    pains: ["content-volume", "repetitive-tasks", "email-overload"],
    monthlyCostUsd: 20,
    setupEffort: "low",
    impact: "high",
    hoursSavedWeekly: 5,
    oneLiner: "General-purpose assistant for drafts, replies and quick analysis.",
    isGeneric: true,
  },
  {
    id: "claude",
    name: "Claude",
    url: "https://claude.ai",
    category: "writing",
    niches: [],
    pains: ["content-volume", "data-analysis", "repetitive-tasks"],
    monthlyCostUsd: 20,
    setupEffort: "low",
    impact: "high",
    hoursSavedWeekly: 5,
    oneLiner: "Long-context assistant strong at documents, analysis and code.",
    isGeneric: true,
  },
  {
    id: "jasper",
    name: "Jasper",
    url: "https://jasper.ai",
    category: "marketing",
    niches: ["agency", "ecommerce"],
    pains: ["content-volume", "seo-visibility"],
    monthlyCostUsd: 49,
    setupEffort: "medium",
    impact: "medium",
    hoursSavedWeekly: 4,
    oneLiner: "Brand-tuned marketing copy at volume across channels.",
  },
  {
    id: "fireflies",
    name: "Fireflies.ai",
    url: "https://fireflies.ai",
    category: "meetings",
    niches: [],
    pains: ["meeting-notes"],
    monthlyCostUsd: 18,
    setupEffort: "low",
    impact: "medium",
    hoursSavedWeekly: 3,
    oneLiner: "Records, transcribes and summarizes meetings automatically.",
  },
  {
    id: "intercom-fin",
    name: "Intercom Fin",
    url: "https://intercom.com/fin",
    category: "support",
    niches: ["saas", "ecommerce"],
    pains: ["customer-support-load", "email-overload"],
    monthlyCostUsd: 99,
    setupEffort: "high",
    impact: "high",
    hoursSavedWeekly: 8,
    oneLiner: "AI agent that resolves front-line support tickets on its own.",
  },
  {
    id: "apollo",
    name: "Apollo.io",
    url: "https://apollo.io",
    category: "sales",
    niches: ["saas", "agency"],
    pains: ["lead-research"],
    monthlyCostUsd: 49,
    setupEffort: "medium",
    impact: "high",
    hoursSavedWeekly: 6,
    oneLiner: "Finds, enriches and sequences outbound leads.",
  },
  {
    id: "make",
    name: "Make",
    url: "https://make.com",
    category: "ops",
    niches: [],
    pains: ["repetitive-tasks", "email-overload"],
    monthlyCostUsd: 16,
    setupEffort: "high",
    impact: "high",
    hoursSavedWeekly: 7,
    oneLiner: "Visual automation to connect apps and kill manual busywork.",
  },
  {
    id: "zapier",
    name: "Zapier",
    url: "https://zapier.com",
    category: "ops",
    niches: [],
    pains: ["repetitive-tasks"],
    monthlyCostUsd: 30,
    setupEffort: "low",
    impact: "medium",
    hoursSavedWeekly: 4,
    oneLiner: "No-code automations between the tools you already use.",
  },
  {
    id: "opus-clip",
    name: "Opus Clip",
    url: "https://opus.pro",
    category: "video",
    niches: ["creator", "agency"],
    pains: ["video-editing", "content-volume"],
    monthlyCostUsd: 29,
    setupEffort: "low",
    impact: "medium",
    hoursSavedWeekly: 4,
    oneLiner: "Turns long videos into ready-to-post short clips.",
  },
  {
    id: "buffer",
    name: "Buffer",
    url: "https://buffer.com",
    category: "marketing",
    niches: [],
    pains: ["social-scheduling", "content-volume"],
    monthlyCostUsd: 12,
    setupEffort: "low",
    impact: "medium",
    hoursSavedWeekly: 3,
    oneLiner: "Schedules and drafts social posts across channels.",
  },
  {
    id: "gamma",
    name: "Gamma",
    url: "https://gamma.app",
    category: "design",
    niches: ["agency", "consulting"],
    pains: ["design-assets", "content-volume"],
    monthlyCostUsd: 10,
    setupEffort: "low",
    impact: "medium",
    hoursSavedWeekly: 2,
    oneLiner: "Generates polished decks and one-pagers from a prompt.",
  },
  {
    id: "hex",
    name: "Hex",
    url: "https://hex.tech",
    category: "data",
    niches: ["saas"],
    pains: ["data-analysis"],
    monthlyCostUsd: 36,
    setupEffort: "high",
    impact: "high",
    hoursSavedWeekly: 6,
    oneLiner: "Notebook + AI for exploring and sharing data analyses.",
  },
];
