"use client";

/**
 * Screen 02 — /drafts/:id (C3 Draft Review — primary compliance screen)
 *
 * docs/04-ux.md §4 Screen 02 wireframe:
 *  - Platform label caption
 *  - AI Disclosure Badge (non-dismissable, WCAG AAA 6.5:1 contrast)
 *  - "About this AI" link → /privacy-policy#ai (SB-942 + EU AI Act Art. 50)
 *  - "Generated by Anthropic Claude Sonnet" subtext
 *  - Platform preview (read-only)
 *  - Draft text (editable textarea)
 *  - "Report this draft" ghost button → ReportDraftModal
 *  - Regenerate instruction input + Regenerate button
 *  - Discard (danger) + Approve & Schedule (primary) — equal font size (48px)
 *
 * Keyboard navigation (docs/04-ux.md §8 focus order steps 4–11):
 *  4. [Focus programmatically set to draft card heading on load]
 *  5. Editable draft textarea (Tab)
 *  6. "About this AI" link (Tab) — from AIBadge component
 *  7. "Report this draft" button (Tab)
 *  8. Regenerate instruction input (Tab)
 *  9. Regenerate button (Tab)
 *  10. Discard button (Tab)
 *  11. Approve & Schedule button (Tab; Enter triggers action) — intentionally last
 *
 * Compliance:
 *  - C5: non-dismissable AI badge present at all times
 *  - C3: no publish path bypasses this screen
 *  - A3: ai_generated flag from API → badge display
 *  - A6/L-UX-2: "Report this draft" → POST /api/drafts/:id/report
 */

import { useState, useEffect, useRef, useId } from "react";
import { useRouter, useParams } from "next/navigation";
import { AIBadge } from "../../../components/AIBadge";
import { ReportDraftModal } from "../../../components/ReportDraftModal";
import { ScheduleModal } from "../../../components/ScheduleModal";
import { BottomNav } from "../../../components/BottomNav";

interface DraftData {
  id: string;
  platform: "linkedin" | "instagram";
  body: string;
  hashtags: string[];
  topic_input: string;
  ai_generated: boolean;
  generation_id: string;
  status: string;
  approved_by: string | null;
  approved_at: string | null;
  created_at: string;
}

type LoadState = "loading" | "loaded" | "error";

export default function DraftReviewPage() {
  const { id: draftId } = useParams<{ id: string }>();
  const router = useRouter();

  const [draft, setDraft] = useState<DraftData | null>(null);
  const [loadState, setLoadState] = useState<LoadState>("loading");
  const [editedBody, setEditedBody] = useState("");
  const [regenInstruction, setRegenInstruction] = useState("");
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [isApproving, setIsApproving] = useState(false);
  const [isDiscarding, setIsDiscarding] = useState(false);
  const [showDiscardConfirm, setShowDiscardConfirm] = useState(false);
  const [showReportModal, setShowReportModal] = useState(false);
  const [showScheduleModal, setShowScheduleModal] = useState(false);
  const [toast, setToast] = useState<{ message: string; type: "success" | "error" } | null>(null);
  const [regenError, setRegenError] = useState<string | null>(null);

  const headingRef = useRef<HTMLHeadingElement>(null);
  const reportButtonRef = useRef<HTMLButtonElement>(null);
  const regenInstructionId = useId();

  // Load draft on mount
  useEffect(() => {
    if (!draftId) return;

    fetch(`/api/drafts/${draftId}`)
      .then((res) => {
        if (!res.ok) throw new Error("Draft not found");
        return res.json();
      })
      .then((data: DraftData) => {
        setDraft(data);
        setEditedBody(data.body ?? "");
        setLoadState("loaded");
        // docs/04-ux.md §8 step 4: focus moves to draft card heading on load
        setTimeout(() => headingRef.current?.focus(), 50);
      })
      .catch(() => {
        setLoadState("error");
      });
  }, [draftId]);

  function showToast(message: string, type: "success" | "error") {
    setToast({ message, type });
    setTimeout(() => setToast(null), 4000);
  }

  async function handleRegenerate() {
    if (!draftId || isRegenerating) return;

    setIsRegenerating(true);
    setRegenError(null);

    try {
      const res = await fetch(`/api/drafts/${draftId}/regenerate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          regen_instructions: regenInstruction.trim() || undefined,
        }),
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        if (res.status === 400 && data.code === "PROMPT_REJECTED") {
          setRegenError("Regeneration instruction contains disallowed content. Please modify and try again.");
          return;
        }
        setRegenError("Regeneration failed. Please try again.");
        return;
      }

      const data = await res.json();
      setDraft((prev) =>
        prev
          ? {
              ...prev,
              body: data.body ?? prev.body,
              hashtags: data.hashtags ?? prev.hashtags,
              generation_id: data.generation_id ?? prev.generation_id,
            }
          : prev
      );
      setEditedBody(data.body ?? "");
      setRegenInstruction("");
    } catch {
      setRegenError("Regeneration failed. Please check your connection.");
    } finally {
      setIsRegenerating(false);
    }
  }

  async function handleApprove() {
    if (!draftId || isApproving) return;

    setIsApproving(true);

    try {
      const res = await fetch(`/api/drafts/${draftId}/approve`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      });

      if (!res.ok) {
        showToast("Approval failed. Please try again.", "error");
        return;
      }

      showToast("Post approved! You can now schedule it.", "success");
      // Update local draft status so Schedule button becomes available
      setDraft((prev) => prev ? { ...prev, status: "approved" } : prev);
    } catch {
      showToast("Approval failed. Please check your connection.", "error");
    } finally {
      setIsApproving(false);
    }
  }

  async function handleDiscard() {
    if (!draftId || isDiscarding) return;

    setIsDiscarding(true);

    try {
      await fetch(`/api/drafts/${draftId}`, { method: "DELETE" });
    } catch {
      // Best-effort discard — navigate anyway
    } finally {
      setIsDiscarding(false);
      router.push("/dashboard");
    }
  }

  // ---- Render ----

  if (loadState === "loading") {
    return (
      <div
        style={{
          minHeight: "100dvh",
          backgroundColor: "var(--color-surface-muted)",
          fontFamily: "var(--font-family)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div aria-live="polite" aria-atomic="true" style={{ color: "var(--color-muted)" }}>
          Loading draft…
        </div>
      </div>
    );
  }

  if (loadState === "error" || !draft) {
    return (
      <div
        style={{
          minHeight: "100dvh",
          backgroundColor: "var(--color-surface-muted)",
          fontFamily: "var(--font-family)",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          gap: "var(--space-4)",
        }}
      >
        <p role="alert" style={{ color: "var(--color-error)" }}>
          Draft not found or you don&apos;t have permission to view it.
        </p>
        <a
          href="/dashboard"
          style={{ color: "var(--color-primary)", textDecoration: "underline" }}
        >
          Return to dashboard
        </a>
      </div>
    );
  }

  const platformLabel =
    draft.platform === "linkedin" ? "LinkedIn" : "Instagram";

  return (
    <div
      style={{
        minHeight: "100dvh",
        backgroundColor: "var(--color-surface-muted)",
        fontFamily: "var(--font-family)",
        display: "flex",
        flexDirection: "column",
      }}
    >
      {/* Toast notification */}
      {toast && (
        <div
          role="status"
          aria-live="polite"
          aria-atomic="true"
          style={{
            position: "fixed",
            top: "var(--space-4)",
            left: "50%",
            transform: "translateX(-50%)",
            zIndex: 100,
            backgroundColor:
              toast.type === "success" ? "var(--color-success)" : "var(--color-error)",
            color: "white",
            padding: "var(--space-3) var(--space-6)",
            borderRadius: "var(--radius-md)",
            fontSize: "var(--font-size-body-sm)",
            fontWeight: "var(--font-weight-medium)",
            boxShadow: "var(--shadow-modal)",
            whiteSpace: "nowrap",
          }}
        >
          {toast.message}
        </div>
      )}

      {/* Header */}
      <header
        style={{
          height: "48px",
          display: "flex",
          alignItems: "center",
          paddingInline: "var(--margin-page-mobile)",
          backgroundColor: "var(--color-surface)",
          borderBottom: "1px solid var(--color-border)",
          flexShrink: 0,
        }}
      >
        <a
          href="/create"
          aria-label="Back to create"
          style={{
            color: "var(--color-primary)",
            fontSize: "var(--font-size-body)",
            textDecoration: "none",
            display: "flex",
            alignItems: "center",
            gap: "4px",
            minHeight: "var(--min-tap-target)",
            minWidth: "var(--min-tap-target)",
          }}
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          >
            <path d="M15 18l-6-6 6-6" />
          </svg>
          Back
        </a>
        <h1
          ref={headingRef}
          tabIndex={-1}
          style={{
            flex: 1,
            textAlign: "center",
            fontSize: "var(--font-size-h3)",
            fontWeight: "var(--font-weight-semibold)",
            color: "var(--color-text)",
            margin: 0,
            outline: "none",
          }}
        >
          Review Draft
        </h1>
        <div style={{ width: "48px" }} aria-hidden="true" />
      </header>

      {/* Main content — scrollable */}
      <main
        style={{
          flex: 1,
          overflowY: "auto",
          padding: "var(--space-4) var(--margin-page-mobile)",
          paddingBottom: `calc(var(--bottom-nav-height) + 80px + var(--space-6))`,
          maxWidth: "600px",
          margin: "0 auto",
          width: "100%",
          boxSizing: "border-box",
        }}
      >
        {/* Draft card */}
        <div
          style={{
            backgroundColor: "var(--color-surface)",
            border: "1px solid var(--color-border)",
            borderRadius: "var(--radius-lg)",
            padding: "var(--space-4)",
            marginBottom: "var(--space-4)",
          }}
        >
          {/* Platform label */}
          <p
            style={{
              fontSize: "var(--font-size-caption)",
              color: "var(--color-muted)",
              marginBottom: "var(--space-2)",
              textTransform: "capitalize",
            }}
          >
            {platformLabel}
          </p>

          {/* AI Disclosure Badge (step 6 in keyboard order via Tab from textarea) */}
          {draft.ai_generated && (
            <div style={{ marginBottom: "var(--space-2)" }}>
              <AIBadge state="pre-approval" />
            </div>
          )}

          {/* "Generated by Anthropic Claude Sonnet" subtext */}
          {draft.ai_generated && (
            <p
              style={{
                fontSize: "var(--font-size-caption)",
                color: "var(--color-muted)",
                marginBottom: "var(--space-3)",
              }}
            >
              Generated by Anthropic Claude Sonnet
            </p>
          )}

          {/* Platform preview (read-only representation) */}
          <div
            aria-label={`${platformLabel} post preview`}
            style={{
              border: "1px solid var(--color-border)",
              borderRadius: "var(--radius-md)",
              padding: "var(--space-3)",
              backgroundColor: "var(--color-surface-muted)",
              marginBottom: "var(--space-3)",
              fontSize: "var(--font-size-body-sm)",
              color: "var(--color-text)",
              whiteSpace: "pre-wrap",
              wordBreak: "break-word",
              minHeight: "60px",
            }}
          >
            {editedBody || draft.body}
            {draft.hashtags?.length > 0 && (
              <div
                style={{
                  marginTop: "var(--space-2)",
                  color: "var(--color-primary)",
                }}
              >
                {draft.hashtags.join(" ")}
              </div>
            )}
          </div>

          {/* Editable draft textarea (step 5 in keyboard order) */}
          <label
            htmlFor="draft-body"
            style={{
              display: "block",
              fontSize: "var(--font-size-h4)",
              fontWeight: "var(--font-weight-semibold)",
              color: "var(--color-text)",
              marginBottom: "var(--space-2)",
            }}
          >
            Draft text
          </label>
          <textarea
            id="draft-body"
            value={editedBody}
            onChange={(e) => setEditedBody(e.target.value)}
            rows={6}
            aria-label="Edit draft text"
            style={{
              width: "100%",
              padding: "var(--space-3)",
              border: `1px solid var(--color-border)`,
              borderRadius: "var(--radius-md)",
              fontSize: "var(--font-size-body)",
              color: "var(--color-text)",
              backgroundColor: "var(--color-surface-muted)",
              resize: "vertical",
              boxSizing: "border-box",
              fontFamily: "var(--font-family)",
            }}
          />
        </div>

        {/* Report this draft button (step 7 in keyboard order) */}
        <button
          ref={reportButtonRef}
          type="button"
          onClick={() => setShowReportModal(true)}
          aria-label="Report a problem with this AI-generated draft"
          style={{
            display: "flex",
            alignItems: "center",
            gap: "var(--space-2)",
            minHeight: "var(--min-tap-target)",
            padding: "0 var(--space-2)",
            backgroundColor: "transparent",
            color: "var(--color-text)",
            border: `1px solid var(--color-border)`,
            borderRadius: "var(--radius-md)",
            fontSize: "var(--font-size-body-sm)",
            cursor: "pointer",
            marginBottom: "var(--space-4)",
          }}
        >
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          >
            <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
            <line x1="4" y1="22" x2="4" y2="15" />
          </svg>
          Report this draft
        </button>

        {/* Regenerate section */}
        <div
          style={{
            backgroundColor: "var(--color-surface)",
            border: "1px solid var(--color-border)",
            borderRadius: "var(--radius-lg)",
            padding: "var(--space-4)",
            marginBottom: "var(--space-4)",
          }}
        >
          <label
            htmlFor={regenInstructionId}
            style={{
              display: "block",
              fontSize: "var(--font-size-h4)",
              fontWeight: "var(--font-weight-semibold)",
              color: "var(--color-text)",
              marginBottom: "var(--space-2)",
            }}
          >
            Regenerate instruction (optional)
          </label>
          {/* Regenerate instruction input (step 8) */}
          <input
            id={regenInstructionId}
            type="text"
            value={regenInstruction}
            onChange={(e) => setRegenInstruction(e.target.value)}
            placeholder="e.g. make it shorter, add a call to action"
            maxLength={500}
            style={{
              width: "100%",
              minHeight: "var(--min-tap-target)",
              padding: "0 var(--space-3)",
              border: `1px solid var(--color-border)`,
              borderRadius: "var(--radius-md)",
              fontSize: "var(--font-size-body)",
              color: "var(--color-text)",
              backgroundColor: "var(--color-surface-muted)",
              boxSizing: "border-box",
              marginBottom: "var(--space-3)",
            }}
          />

          {regenError && (
            <p
              role="alert"
              style={{
                color: "var(--color-error)",
                fontSize: "var(--font-size-body-sm)",
                marginBottom: "var(--space-2)",
              }}
            >
              {regenError}
            </p>
          )}

          {/* Regenerate button (step 9) */}
          <button
            type="button"
            onClick={handleRegenerate}
            disabled={isRegenerating}
            aria-busy={isRegenerating}
            style={{
              width: "100%",
              minHeight: "var(--min-button-height)",
              backgroundColor: "white",
              color: isRegenerating ? "var(--color-muted)" : "var(--color-primary)",
              border: `1px solid ${isRegenerating ? "var(--color-border)" : "var(--color-primary)"}`,
              borderRadius: "var(--radius-md)",
              fontSize: "var(--font-size-body)",
              fontWeight: "var(--font-weight-semibold)",
              cursor: isRegenerating ? "not-allowed" : "pointer",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              gap: "var(--space-2)",
            }}
          >
            {isRegenerating ? (
              <>
                <svg
                  width="16"
                  height="16"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  aria-hidden="true"
                  style={{ animation: "spin 1s linear infinite" }}
                >
                  <path d="M21 12a9 9 0 1 1-6.219-8.56" />
                </svg>
                Regenerating…
              </>
            ) : (
              "Regenerate"
            )}
          </button>
        </div>
      </main>

      {/* Fixed action bar — Discard + Approve + Schedule (steps 10–12) */}
      <div
        style={{
          position: "fixed",
          bottom: "var(--bottom-nav-height)",
          left: 0,
          right: 0,
          zIndex: 10,
          backgroundColor: "var(--color-surface)",
          borderTop: "1px solid var(--color-border)",
          padding: "var(--space-3) var(--margin-page-mobile)",
          display: "flex",
          gap: "var(--space-2)",
        }}
      >
        {/* Discard button (step 10) — danger variant */}
        <button
          type="button"
          onClick={() => setShowDiscardConfirm(true)}
          aria-label="Discard this draft"
          disabled={isApproving}
          style={{
            flex: 1,
            minHeight: "var(--min-button-height)",
            backgroundColor: "white",
            color: "var(--color-error)",
            border: `1px solid var(--color-error)`,
            borderRadius: "var(--radius-md)",
            fontSize: "var(--font-size-body)",
            fontWeight: "var(--font-weight-semibold)",
            cursor: isApproving ? "not-allowed" : "pointer",
          }}
        >
          Discard
        </button>

        {/* Approve button (step 11) — approves draft, enabling Schedule */}
        {draft.status !== "approved" && draft.status !== "scheduled" && (
          <button
            type="button"
            onClick={handleApprove}
            aria-label="Approve this AI-generated post"
            disabled={isApproving}
            aria-busy={isApproving}
            style={{
              flex: 2,
              minHeight: "var(--min-button-height)",
              backgroundColor: isApproving ? "var(--color-border)" : "var(--color-primary)",
              color: isApproving ? "var(--color-muted)" : "white",
              border: "none",
              borderRadius: "var(--radius-md)",
              fontSize: "var(--font-size-body)",
              fontWeight: "var(--font-weight-semibold)",
              cursor: isApproving ? "not-allowed" : "pointer",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              gap: "var(--space-2)",
            }}
          >
            {isApproving ? (
              <>
                <svg
                  width="16"
                  height="16"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  aria-hidden="true"
                  style={{ animation: "spin 1s linear infinite" }}
                >
                  <path d="M21 12a9 9 0 1 1-6.219-8.56" />
                </svg>
                Approving…
              </>
            ) : (
              "Approve"
            )}
          </button>
        )}

        {/* Schedule button (step 12) — visible after approval, opens ScheduleModal */}
        {(draft.status === "approved" || draft.status === "scheduled") && (
          <button
            type="button"
            onClick={() => setShowScheduleModal(true)}
            aria-label="Schedule this approved post for publishing"
            style={{
              flex: 2,
              minHeight: "var(--min-button-height)",
              backgroundColor: "var(--color-primary)",
              color: "white",
              border: "none",
              borderRadius: "var(--radius-md)",
              fontSize: "var(--font-size-body)",
              fontWeight: "var(--font-weight-semibold)",
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              gap: "var(--space-2)",
            }}
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden="true"
            >
              <rect x="3" y="4" width="18" height="18" rx="2" ry="2" />
              <line x1="16" y1="2" x2="16" y2="6" />
              <line x1="8" y1="2" x2="8" y2="6" />
              <line x1="3" y1="10" x2="21" y2="10" />
            </svg>
            Schedule
          </button>
        )}
      </div>

      {/* Discard confirmation dialog */}
      {showDiscardConfirm && (
        <>
          <div
            onClick={() => setShowDiscardConfirm(false)}
            aria-hidden="true"
            style={{
              position: "fixed",
              inset: 0,
              backgroundColor: "rgba(0, 0, 0, 0.4)",
              zIndex: 50,
            }}
          />
          <div
            role="dialog"
            aria-modal="true"
            aria-labelledby="discard-confirm-title"
            style={{
              position: "fixed",
              top: "50%",
              left: "50%",
              transform: "translate(-50%, -50%)",
              zIndex: 51,
              backgroundColor: "var(--color-surface)",
              borderRadius: "var(--radius-modal)",
              padding: "var(--space-6)",
              width: "min(400px, calc(100vw - 32px))",
              boxShadow: "var(--shadow-modal)",
            }}
          >
            <h2
              id="discard-confirm-title"
              style={{
                fontSize: "var(--font-size-h3)",
                fontWeight: "var(--font-weight-semibold)",
                color: "var(--color-text)",
                marginBottom: "var(--space-3)",
              }}
            >
              Discard this draft?
            </h2>
            <p
              style={{
                fontSize: "var(--font-size-body)",
                color: "var(--color-muted)",
                marginBottom: "var(--space-4)",
              }}
            >
              This draft will be permanently removed.
            </p>
            <div style={{ display: "flex", gap: "var(--space-3)" }}>
              <button
                type="button"
                onClick={() => setShowDiscardConfirm(false)}
                style={{
                  flex: 1,
                  minHeight: "var(--min-button-height)",
                  backgroundColor: "transparent",
                  color: "var(--color-text)",
                  border: `1px solid var(--color-border)`,
                  borderRadius: "var(--radius-md)",
                  fontSize: "var(--font-size-body)",
                  cursor: "pointer",
                }}
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={() => {
                  setShowDiscardConfirm(false);
                  handleDiscard();
                }}
                disabled={isDiscarding}
                style={{
                  flex: 1,
                  minHeight: "var(--min-button-height)",
                  backgroundColor: "white",
                  color: "var(--color-error)",
                  border: `1px solid var(--color-error)`,
                  borderRadius: "var(--radius-md)",
                  fontSize: "var(--font-size-body)",
                  fontWeight: "var(--font-weight-semibold)",
                  cursor: isDiscarding ? "not-allowed" : "pointer",
                }}
              >
                {isDiscarding ? "Discarding…" : "Discard"}
              </button>
            </div>
          </div>
        </>
      )}

      {/* Report Draft Modal (A6/L-UX-2) */}
      <ReportDraftModal
        draftId={draftId}
        isOpen={showReportModal}
        onClose={() => setShowReportModal(false)}
      />

      {/* Schedule Modal (C2) */}
      <ScheduleModal
        draftId={draftId}
        isOpen={showScheduleModal}
        onClose={() => setShowScheduleModal(false)}
      />

      <BottomNav />

      <style>{`
        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
        textarea:focus-visible,
        input:focus-visible,
        button:focus-visible,
        a:focus-visible {
          outline: var(--focus-outline-width) solid var(--color-focus-outline);
          outline-offset: var(--focus-outline-offset);
        }
      `}</style>
    </div>
  );
}
