"use client";

/**
 * AIBadge — non-dismissable AI disclosure badge
 *
 * Compliance: EU AI Act Art. 50, FTC §5, C5 AC
 *  - Non-dismissable (no close control)
 *  - WCAG AAA contrast: #1E40AF on #EFF6FF = 6.5:1
 *  - Present pre-approval ("AI-generated draft") and post-approval ("AI-generated content · reviewed by [name]")
 *  - Screen reader: role="status", aria-label per docs/04-ux.md §8
 *  - Never removed when user edits draft
 *  - "About this AI" inline link (CA SB-942 + EU AI Act transparency)
 *
 * docs/04-ux.md §4 Screen 02, §5 AI Badge component, §7 AI Transparency UX
 */

interface AIBadgeProps {
  /** 'pre-approval': shows "AI-generated draft"; 'post-approval': shows reviewed-by variant */
  state: "pre-approval" | "post-approval";
  /** User's display name — required when state='post-approval' */
  reviewerName?: string;
}

export function AIBadge({ state, reviewerName }: AIBadgeProps) {
  const label =
    state === "pre-approval"
      ? "This post was generated by AI"
      : `AI-generated content, reviewed by ${reviewerName ?? "user"}`;

  const badgeText =
    state === "pre-approval"
      ? "AI-generated draft"
      : `AI-generated content · reviewed by ${reviewerName ?? "user"}`;

  return (
    <div
      role="status"
      aria-label={label}
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: "6px",
        backgroundColor: "var(--color-badge-ai-bg)",
        color: "var(--color-badge-ai-text)",
        padding: "4px 10px",
        borderRadius: "var(--radius-pill)",
        fontSize: "var(--font-size-body-sm)",
        fontWeight: "var(--font-weight-medium)",
        // No close button — non-dismissable per compliance
      }}
    >
      {/* Sparkles icon (Lucide equivalent as SVG inline — no JS library dependency for SSR) */}
      <svg
        width="14"
        height="14"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
      >
        <path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z" />
      </svg>

      <span>{badgeText}</span>

      {/* "About this AI" link — CA SB-942 + EU AI Act transparency (docs/04-ux.md §7) */}
      <a
        href="/privacy-policy#ai"
        target="_blank"
        rel="noopener noreferrer"
        aria-label="Learn about the AI model used; opens in new tab"
        style={{
          color: "var(--color-badge-ai-text)",
          fontSize: "var(--font-size-body-sm)",
          textDecoration: "underline",
          marginLeft: "4px",
          // Minimum tap target — link is inline; parent badge provides context
        }}
      >
        About this AI
        <svg
          width="10"
          height="10"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
          style={{ marginLeft: "2px", verticalAlign: "middle" }}
        >
          <path d="M15 3h6v6" />
          <path d="M10 14 21 3" />
          <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
        </svg>
      </a>
    </div>
  );
}
