-- source_provenance (#159A, from the Signal-Engine spec's golden rule #2):
-- every external signal we collect must answer, in one place, "under which
-- terms, under which legal basis, and for how long?".
--
-- Before this table those answers lived in code comments (reddit-signal.ts
-- says "public SERP results, NOT the Reddit Data API") — true, but invisible
-- to the ROPA (#142), to DPA reviews (#143), and to the enterprise DPO who
-- gatekeeps agency deals. A registry the compliance artifacts can JOIN against
-- is what turns "we behave well" into "we can show it".
--
-- Reference data, not per-tenant data: no RLS, readable by the app role.
-- Rows are UPDATED when a ToS version or retention decision changes — the
-- registry describes the CURRENT collection contract; history lives in git.

CREATE TABLE IF NOT EXISTS source_registry (
  id               TEXT PRIMARY KEY,          -- stable slug referenced by signal rows
  source_type      TEXT NOT NULL,             -- llm_answer | serp | social_public | web_crawl | first_party | places
  platform         TEXT NOT NULL,             -- human-readable origin
  collection_method TEXT NOT NULL,            -- how we obtain it (api_query, direct_fetch, user_input)
  -- ToS identity under which collection happens. Not a marketing string: when
  -- a provider revises terms, this value changes in a reviewed migration.
  tos_version      TEXT NOT NULL,
  -- GDPR Art. 6 / LGPD Art. 7 basis for the collection.
  legal_basis      TEXT NOT NULL
                     CHECK (legal_basis IN ('legitimate_interest', 'contract', 'consent')),
  -- Days raw collected text is retained before purge. NULL = kept for the
  -- life of the account (first-party data under contract). 0 = never stored
  -- raw (aggregates only).
  retention_days   INTEGER,
  notes            TEXT NOT NULL DEFAULT ''
);

-- The registry as it stands on 2026-08-06. tos_version records the terms in
-- force when the integration shipped; a provider ToS change is a migration.
INSERT INTO source_registry (id, source_type, platform, collection_method, tos_version, legal_basis, retention_days, notes) VALUES
  ('provider_answer', 'llm_answer', 'anthropic/openai/gemini/perplexity', 'api_query',
   'provider-api-terms-2026-06', 'legitimate_interest', 90,
   'Answers generated by AI engines to synthetic buyer-intent prompts about the client''s own brand (GEO-A2: never a competitor''s). query_text purged to NULL after 90d (existing pg_cron); query_hash retained. ZDR flags recorded per call in ai_generation_log.'),
  ('serp_public_search', 'serp', 'google-via-dataforseo', 'api_query',
   'dataforseo-terms-2026-06', 'legitimate_interest', 90,
   'Public Google results (organic + AI Overview) for the client''s own brand. Same 90d text purge as provider answers.'),
  ('reddit_via_serp', 'social_public', 'reddit.com (public results via SERP)', 'api_query',
   'dataforseo-terms-2026-06', 'legitimate_interest', 0,
   'RED LINE: NOT the Reddit Data API — that path requires a Reddit commercial data licence AND the GEO-A1 FTC disclosure, and stays gated until both exist. Only aggregates are stored (thread counts, subreddit names, derived sentiment): no usernames, no comment bodies, no raw snippets.'),
  ('site_crawl_client', 'web_crawl', 'client''s own website', 'direct_fetch',
   'client-authorization-in-tos', 'contract', 90,
   'The client''s own site, crawled at their request as part of the audit they bought. SSRF-guarded (ssrf-guard.ts).'),
  ('google_places', 'places', 'google-maps-platform', 'api_query',
   'google-maps-platform-terms-2026-07', 'contract', 0,
   'The client''s own Maps listing (name, address, reviews) attached by the client in the Pages builder. Pulled fresh on every generate, not warehoused (Maps ToS caching limits).'),
  ('client_supplied', 'first_party', 'in-app input', 'user_input',
   'ozvor-tos-current', 'contract', NULL,
   'Brand names, domains, profile URLs, business descriptions typed by the client. First-party data under the subscription contract; kept for the life of the account, deleted with it.')
ON CONFLICT (id) DO UPDATE SET
  source_type = EXCLUDED.source_type,
  platform = EXCLUDED.platform,
  collection_method = EXCLUDED.collection_method,
  tos_version = EXCLUDED.tos_version,
  legal_basis = EXCLUDED.legal_basis,
  retention_days = EXCLUDED.retention_days,
  notes = EXCLUDED.notes;

-- The FK from collected signals to their provenance. citation_check is the
-- per-probe evidence row — the one table where collected external text lands.
-- (Offsite/Reddit aggregates ride inside geo_score.provider_breakdown JSON and
-- carry no raw text; their provenance is the registry rows themselves.)
-- Nullable: rows predating this migration stay NULL rather than being
-- back-stamped with a provenance we did not record at collection time.
ALTER TABLE citation_check
  ADD COLUMN IF NOT EXISTS source_id TEXT REFERENCES source_registry (id);
