/**
 * /legal/sub-processors — Sub-Processors list (public, standalone)
 *
 * Grounded in docs/legal/sub-processors.md and Privacy Policy §4.
 * Lists the 11 sub-processors that may process personal data on behalf of
 * Ozvor customers: Supabase, Anthropic, OpenAI, Google (Gemini),
 * Perplexity, DataForSEO, SerpAPI, Stripe, Resend, Railway, Cloudflare.
 *
 * Art. 28 GDPR / LGPD mechanism note included; change-notification process
 * described; DPA cross-reference provided.
 *
 * Linked from: site Footer ("Sub-processors") + DPA page §5
 * No login required (public page).
 */

import { LegalPage, LegalSection } from "../../../components/legal/LegalPage";

export const metadata = {
  title: "Sub-Processors | Ozvor",
  description:
    "Current list of sub-processors that may process personal data on behalf of Ozvor customers, including transfer mechanisms and data categories.",
  alternates: { canonical: "https://ozvor.com/legal/sub-processors" },
  openGraph: {
    title: "Sub-Processors | Ozvor",
    description:
      "Current list of sub-processors that may process personal data on behalf of Ozvor customers, including transfer mechanisms and data categories.",
    url: "https://ozvor.com/legal/sub-processors",
    siteName: "Ozvor",
    type: "website",
  },
  robots: {
    index: true,
    follow: false,
  },
};

/* ── shared table cell styles ── */
const cell: React.CSSProperties = {
  padding: "8px 10px",
  borderBottom: "1px solid var(--color-border)",
  verticalAlign: "top",
  fontSize: "var(--font-size-caption)",
  lineHeight: 1.6,
  color: "var(--color-text)",
};

const th: React.CSSProperties = {
  ...cell,
  fontWeight: 700,
  color: "var(--color-muted)",
  textAlign: "left",
  backgroundColor: "var(--color-surface-muted)",
};

const linkStyle: React.CSSProperties = {
  color: "var(--color-primary)",
  textDecoration: "none",
};

export default function SubProcessorsPage() {
  return (
    <LegalPage
      title="Sub-Processors"
      updated="24 June 2026"
      intro="This page lists all sub-processors engaged by Ozvor that may process personal data submitted to or generated by the Service on behalf of our customers. Ozvor is operated by Ozvor (a company being incorporated in Brazil) and acts as a data processor with respect to personal data you submit through the Service. This list is maintained in accordance with Art. 28 GDPR, Art. 14 LGPD, and our Data Processing Agreement (DPA)."
    >
      <LegalSection n="1" title="Our obligations under Art. 28 GDPR / LGPD">
        <p>
          We engage sub-processors only on the basis of a written contract
          (DPA) that imposes data-protection obligations equivalent to those
          in our agreement with you. We remain liable for the performance of
          each sub-processor with respect to its data-protection obligations.
        </p>
        <p>
          Before engaging any new sub-processor, or materially changing the
          role of an existing one, we will provide customers with at least{" "}
          <strong>30 days' advance notice</strong> (see Section 3). You may
          object to a new sub-processor within the notice period by contacting{" "}
          <a href="mailto:dpo@ozvor.com" style={linkStyle}>
            dpo@ozvor.com
          </a>
          . If we cannot accommodate the objection, either party may terminate
          the affected services on written notice.
        </p>
      </LegalSection>

      <LegalSection n="2" title="Current sub-processors (11)">
        <p>
          The following 11 sub-processors are currently authorised. Data
          processed is limited to what is necessary for the stated purpose; by
          design, our AI audit prompts are synthetic and contain no personal
          data, and competitor names are never transmitted to AI providers.
        </p>

        <div style={{ overflowX: "auto", marginTop: "var(--space-3)" }}>
          <table
            style={{ width: "100%", borderCollapse: "collapse" }}
            aria-label="Ozvor sub-processors"
          >
            <thead>
              <tr>
                <th style={th}>Sub-processor</th>
                <th style={th}>Purpose / role</th>
                <th style={th}>Data categories processed</th>
                <th style={th}>Region / location</th>
                <th style={th}>Transfer mechanism (EEA/BR → third country)</th>
                <th style={th}>Privacy / DPA notice</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style={cell}>
                  <strong>Supabase</strong>
                </td>
                <td style={cell}>
                  Database (PostgreSQL) and authentication. Stores account
                  data, brand profiles, audit records, and subscription state.
                </td>
                <td style={cell}>
                  Account identifiers (email, Supabase user ID), brand/domain
                  data, audit results, billing state, audit logs
                </td>
                <td style={cell}>
                  EU users: eu-central-1 (Frankfurt, EU).{" "}
                  US users: us-east-1 (US).
                </td>
                <td style={cell}>
                  EU project: data stays in EU — no third-country transfer.{" "}
                  US project: domestic US.
                </td>
                <td style={cell}>
                  <a
                    href="https://supabase.com/privacy"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    supabase.com/privacy
                  </a>{" "}
                  ·{" "}
                  <a
                    href="https://supabase.com/dpa"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    DPA
                  </a>
                </td>
              </tr>
              <tr>
                <td style={cell}>
                  <strong>Anthropic</strong>
                </td>
                <td style={cell}>
                  AI inference — processes synthetic audit prompts to generate
                  citation and presence analysis. Per Anthropic API terms,
                  prompts and responses are not used for training and are not
                  retained beyond returning the result.
                </td>
                <td style={cell}>
                  Synthetic prompt text (brand name + category question; no
                  personal data by design). No competitor names transmitted.
                </td>
                <td style={cell}>
                  Anthropic API (US-hosted). EU-region inference is on our
                  roadmap; current transfers rely on SCCs (Module 2).
                </td>
                <td style={cell}>
                  SCCs (Module 2); DPF certified. EU-region inference planned
                  (roadmap); we disclose here when it ships.
                </td>
                <td style={cell}>
                  <a
                    href="https://www.anthropic.com/privacy"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    anthropic.com/privacy
                  </a>
                </td>
              </tr>
              <tr>
                <td style={cell}>
                  <strong>OpenAI</strong>
                </td>
                <td style={cell}>
                  AI inference — processes synthetic audit prompts for ChatGPT
                  citation and presence analysis. Per OpenAI API terms,
                  prompts are not used for training by default.
                </td>
                <td style={cell}>
                  Synthetic prompt text (brand name + category question; no
                  personal data by design).
                </td>
                <td style={cell}>
                  US-hosted (OpenAI API); EU-hosted path used for EU users
                  where available.
                </td>
                <td style={cell}>
                  SCCs (Module 2); DPF certified.
                </td>
                <td style={cell}>
                  <a
                    href="https://openai.com/policies/privacy-policy"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    openai.com/privacy
                  </a>
                </td>
              </tr>
              <tr>
                <td style={cell}>
                  <strong>Google (Gemini)</strong>
                </td>
                <td style={cell}>
                  AI inference — processes synthetic audit prompts for Google
                  AI Overview and Gemini citation analysis.
                </td>
                <td style={cell}>
                  Synthetic prompt text (brand name + category question; no
                  personal data by design).
                </td>
                <td style={cell}>
                  EU-hosted paths preferred for EU users; US fallback otherwise.
                </td>
                <td style={cell}>
                  SCCs; DPF certified; Google Cloud DPA covers Gemini API usage.
                </td>
                <td style={cell}>
                  <a
                    href="https://policies.google.com/privacy"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    policies.google.com/privacy
                  </a>
                </td>
              </tr>
              <tr>
                <td style={cell}>
                  <strong>Perplexity</strong>
                </td>
                <td style={cell}>
                  AI inference — processes synthetic audit prompts for
                  Perplexity citation analysis.{" "}
                  <strong>
                    Excluded for EU users pending confirmation of transfer
                    safeguards.
                  </strong>
                </td>
                <td style={cell}>
                  Synthetic prompt text (brand name + category question; no
                  personal data by design). US users only at this time.
                </td>
                <td style={cell}>US-hosted.</td>
                <td style={cell}>
                  Transfer safeguards under review; EU users excluded until
                  confirmed.
                </td>
                <td style={cell}>
                  <a
                    href="https://www.perplexity.ai/hub/legal/privacy-policy"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    perplexity.ai/privacy
                  </a>
                </td>
              </tr>
              <tr>
                <td style={cell}>
                  <strong>DataForSEO</strong>
                </td>
                <td style={cell}>
                  Public off-site signal collection — fetches publicly
                  available domain authority, backlink, and search-result data
                  to support Ozvor AI Visibility Score calculation.
                </td>
                <td style={cell}>
                  Brand domain / URL (publicly available). No personal data
                  transmitted.
                </td>
                <td style={cell}>US / EU infrastructure.</td>
                <td style={cell}>
                  No personal data transferred; no transfer mechanism required.
                </td>
                <td style={cell}>
                  <a
                    href="https://dataforseo.com/privacy-policy"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    dataforseo.com/privacy
                  </a>
                </td>
              </tr>
              <tr>
                <td style={cell}>
                  <strong>SerpAPI</strong>
                </td>
                <td style={cell}>
                  Public search-result signal collection — fetches Google AI
                  Overview and traditional SERP data to support Ozvor AI Visibility Score
                  calculation.
                </td>
                <td style={cell}>
                  Brand name / domain (publicly available). No personal data
                  transmitted.
                </td>
                <td style={cell}>US-hosted.</td>
                <td style={cell}>
                  No personal data transferred; no transfer mechanism required.
                </td>
                <td style={cell}>
                  <a
                    href="https://serpapi.com/privacy"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    serpapi.com/privacy
                  </a>
                </td>
              </tr>
              <tr>
                <td style={cell}>
                  <strong>Stripe</strong>
                </td>
                <td style={cell}>
                  Payment processing and subscription management. Billing,
                  invoicing, and subscription lifecycle. Card and payment data
                  is Stripe-hosted; Ozvor never stores full card
                  details.
                </td>
                <td style={cell}>
                  Account name, email, Stripe customer ID (stored in our
                  database); full payment/card data is held exclusively by
                  Stripe.
                </td>
                <td style={cell}>US-hosted (Stripe global infrastructure).</td>
                <td style={cell}>
                  SCCs (Module 2); DPF certified.
                </td>
                <td style={cell}>
                  <a
                    href="https://stripe.com/privacy"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    stripe.com/privacy
                  </a>{" "}
                  ·{" "}
                  <a
                    href="https://stripe.com/legal/dpa"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    DPA
                  </a>
                </td>
              </tr>
              <tr>
                <td style={cell}>
                  <strong>Resend</strong>
                </td>
                <td style={cell}>
                  Transactional email delivery — account notifications, DSR
                  acknowledgements, subscription confirmations, and service
                  alerts.
                </td>
                <td style={cell}>
                  Recipient email address, notification content (no sensitive
                  personal data in email bodies by design).
                </td>
                <td style={cell}>
                  EU infrastructure selected for EU users where available.
                </td>
                <td style={cell}>SCCs where applicable.</td>
                <td style={cell}>
                  <a
                    href="https://resend.com/legal/privacy-policy"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    resend.com/privacy
                  </a>
                </td>
              </tr>
              <tr>
                <td style={cell}>
                  <strong>Railway</strong>
                </td>
                <td style={cell}>
                  Application hosting — runs the Next.js frontend and the API
                  backend. Processes traffic data, environment variables
                  (secrets), and application logs.
                </td>
                <td style={cell}>
                  Traffic data, session tokens in transit, application logs
                  (no persistent personal data logged by design).
                </td>
                <td style={cell}>
                  Region selected per deployment; EU region preferred for EU
                  users.
                </td>
                <td style={cell}>
                  SCCs where non-EU region is used.
                </td>
                <td style={cell}>
                  <a
                    href="https://railway.app/legal/privacy"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    railway.app/privacy
                  </a>
                </td>
              </tr>
              <tr>
                <td style={cell}>
                  <strong>Cloudflare</strong>
                </td>
                <td style={cell}>
                  CDN, DNS, and network security (DDoS protection, TLS
                  termination, edge caching for static assets).
                </td>
                <td style={cell}>
                  IP addresses and HTTP request metadata (processed in transit;
                  subject to Cloudflare's data retention limits).
                </td>
                <td style={cell}>
                  Global edge network; EU traffic routed through EU PoPs.
                </td>
                <td style={cell}>
                  SCCs; DPF certified.
                </td>
                <td style={cell}>
                  <a
                    href="https://www.cloudflare.com/privacypolicy/"
                    style={linkStyle}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    cloudflare.com/privacy
                  </a>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </LegalSection>

      <LegalSection n="3" title="Change notification process">
        <p>
          Ozvor will provide at least <strong>30 days' advance
          notice</strong> before engaging a new sub-processor or materially
          changing the role of an existing one. Notification will be made by:
        </p>
        <ul style={{ paddingLeft: "var(--space-5)", margin: "0 0 var(--space-3) 0" }}>
          <li>
            Email to the primary contact on record for customers who have
            executed a DPA with Ozvor; and
          </li>
          <li>
            An update to this page (the "Last updated" date will reflect the
            change).
          </li>
        </ul>
        <p>
          To object to a new sub-processor, contact{" "}
          <a href="mailto:dpo@ozvor.com" style={linkStyle}>
            dpo@ozvor.com
          </a>{" "}
          within the 30-day notice period, stating the sub-processor and the
          reason for objection. If Ozvor cannot reasonably accommodate
          the objection without materially affecting the Service, either party
          may elect to terminate the affected services on written notice.
        </p>
      </LegalSection>

      <LegalSection n="4" title="Data Processing Agreement (DPA)">
        <p>
          This sub-processor list forms part of the{" "}
          <a href="/legal/dpa" style={linkStyle}>
            Ozvor Data Processing Agreement
          </a>
          , which governs our obligations as a processor under GDPR Art. 28
          and LGPD Art. 14. By using the Service, customers who are themselves
          data controllers accept the DPA, which authorises Ozvor to
          engage the sub-processors listed above on the terms described therein.
        </p>
        <p>
          For questions about sub-processors, data transfers, or to request a
          copy of a specific DPA, contact{" "}
          <a href="mailto:dpo@ozvor.com" style={linkStyle}>
            dpo@ozvor.com
          </a>
          .
        </p>
      </LegalSection>

      <LegalSection n="5" title="Related documents">
        <ul style={{ paddingLeft: "var(--space-5)", margin: "0 0 var(--space-3) 0" }}>
          <li>
            <a href="/privacy-policy" style={linkStyle}>
              Privacy Policy
            </a>{" "}
            — §4 contains an inline summary of sub-processors; §5 covers
            international transfer safeguards.
          </li>
          <li>
            <a href="/legal/dpa" style={linkStyle}>
              Data Processing Agreement
            </a>{" "}
            — the contract governing our obligations as processor.
          </li>
          <li>
            <a href="/legal/dsr-request" style={linkStyle}>
              Data Subject Request
            </a>{" "}
            — exercise your access, deletion, portability, or correction rights.
          </li>
        </ul>
      </LegalSection>
    </LegalPage>
  );
}
